name: link_prediction
model_name: mlp

data:
  data_root: data\citeseer
  dataset: citeseer
  num_workers: 1

# model for data
model:
  _target_: models.mlp.MLP_prop
  in_channels: 3703
  out_channels: 32
  num_hid: 32
  dropout: 0.3

# optimizer1 is for full model training, optimizer 2 is for further tuning of sample layers
optimizer1:
  _target_: torch.optim.Adam
  lr: 0.005
  weight_decay: 0.0005

optimizer2:
  _target_: torch.optim.Adam
  lr: 0.0005
  weight_decay: 0.0005


# lr scheduler for training task optimizer
lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [100, 125, 150, 175]
  gamma: 0.2

# epoch is #epoch for full model training, save_num_model is for sampling
epoch: 200
save_num_model: 100

# name of target layers
train_layer: ['lin2.bias', 'lin2.weight']

# parameter data root
param:
  data_root: param_data/link/mlp/citeseer/data.pt
  k: 50
  num_workers: 4
