defaults:
  - task: gcn2_cora  # Change task, format "model_dataset"
  - system: ae_ddpm_gcn2_cora # Change system, format "ae_ddpm_model_dataset"
  - _self_

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:${device.id}

checkpoint_path: #outputs\cora\gcn2\GNN_Diff\last.ckpt
load_system_checkpoint:
mode: train
seed: 7
process_title: gnn-diff

output_dir: outputs/

hydra:
  output_subdir: config
  run:
    dir: ${output_dir}
  sweep:
    dir: ${output_dir}
    subdir: ${hydra.job.override_dirname}